In [1]:
import numpy as np

print(np.__version__)


2.3.4


Create random 100 data with seed(int) so that for now we get same random data.
Create (100, 3) shape array.

In [2]:
np.random.seed(42) 

ages = np.random.randint(21, 60, 100)
experience = np.random.randint(0, 40, 100)
salaries = np.random.randint(30000, 150000, 100)

data = np.column_stack((ages, experience, salaries))
data[:5]  


array([[    59,     34, 121906],
       [    49,     39,  79811],
       [    35,     21,  32811],
       [    28,     26,  86250],
       [    41,     34, 142547]], dtype=int32)

In [3]:
print("Shape:", data.shape)
print("Data type:", data.dtype)
print("Dimensions:", data.ndim)


Shape: (100, 3)
Data type: int32
Dimensions: 2


In [4]:
print("Average age:", np.mean(data[:, 0]))
print("Median experience:", np.median(data[:, 1]))
print("Highest salary:", np.max(data[:, 2]))
print("Salary standard deviation:", np.std(data[:, 2]))


Average age: 39.43
Median experience: 22.5
Highest salary: 149181
Salary standard deviation: 36883.45050029213


now find the 40+ with top 5 highest salary

In [5]:
high_paid = data[(data[:, 0] > 40) & (data[:, 2] > 100000)]
print("Count:", high_paid.shape[0])
high_paid[:5]


Count: 22


array([[    59,     34, 121906],
       [    41,     34, 142547],
       [    59,      0, 102082],
       [    43,     36, 125742],
       [    44,     25, 113763]], dtype=int32)

In [6]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

print(matrix * 10)

print("Row sums:", matrix.sum(axis=1))
print("Column sums:", matrix.sum(axis=0))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Row sums: [10 26 42]
Column sums: [15 18 21 24]


In [7]:
corr = np.corrcoef(data[:, 1], data[:, 2])[0, 1]
print("Correlation (Experience vs Salary):", corr)

Correlation (Experience vs Salary): 0.043772650126399235


In [8]:
np.save('employee_data.npy', data)

loaded = np.load('employee_data.npy')
print(loaded.shape)


(100, 3)
